# Site settings
title: Bob Scott's Tech Blog
email: bob@robertscottconsulting.com
description: > # this means to ignore newlines until "baseurl:"
  Bob Scott's blog for all things tech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.robertscottconsulting.com" # the base hostname & protocol for your site
twitter_username: bobalooooooo
github_username:  magicclaw

# Build settings
markdown: kramdown
